# Custom Secret Scanning Patterns for INSA Automation Corp
# GitHub Advanced Security will scan for these patterns in addition to default patterns

patterns:
  # INSA-specific API keys
  - name: INSA API Key
    regex: 'insa_api_[a-zA-Z0-9]{32,64}'
    description: "INSA Automation Corp internal API key"

  - name: INSA Service Token
    regex: 'insa_token_[a-zA-Z0-9\-_]{40,}'
    description: "INSA service authentication token"

  # Database credentials
  - name: INSA Database Password
    regex: 'DB_PASSWORD\s*[:=]\s*["\']?[\w\-@!#$%^&*()]{16,}["\']?'
    description: "Database password in configuration files"

  - name: PostgreSQL Connection String
    regex: 'postgres(?:ql)?://[^:]+:[^@]+@[^/]+/\w+'
    description: "PostgreSQL connection string with credentials"

  # AI/ML API keys
  - name: Claude API Key
    regex: 'sk-ant-api[a-zA-Z0-9\-]{40,}'
    description: "Anthropic Claude API key"

  - name: Anthropic API Key
    regex: 'anthropic_api_key_[a-zA-Z0-9]{40,}'
    description: "Anthropic API authentication key"

  - name: OpenAI API Key
    regex: 'sk-[a-zA-Z0-9]{48,}'
    description: "OpenAI API key"

  # GitHub tokens
  - name: GitHub Personal Access Token
    regex: 'ghp_[a-zA-Z0-9]{36,}'
    description: "GitHub personal access token"

  - name: GitHub OAuth Token
    regex: 'gho_[a-zA-Z0-9]{36,}'
    description: "GitHub OAuth access token"

  # Cloud provider credentials
  - name: Azure Connection String
    regex: 'DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[^;]+;?'
    description: "Azure Storage connection string"

  - name: AWS Access Key
    regex: 'AKIA[0-9A-Z]{16}'
    description: "AWS Access Key ID"

  - name: AWS Secret Key
    regex: 'aws_secret_access_key\s*[:=]\s*["\']?[A-Za-z0-9/+=]{40}["\']?'
    description: "AWS Secret Access Key"

  # Industrial/IoT credentials
  - name: ThingsBoard Access Token
    regex: 'Bearer\s+[A-Za-z0-9]{20,}'
    description: "ThingsBoard device access token"

  - name: Modbus TCP Password
    regex: 'modbus_password\s*[:=]\s*["\'][\w\-@!#$%^&*()]{8,}["\']'
    description: "Modbus TCP authentication password"

  # Generic patterns
  - name: Generic Password in Config
    regex: 'password\s*[:=]\s*["\'][\w\-@!#$%^&*()]{8,}["\']'
    description: "Password field in configuration files"

  - name: Generic API Key
    regex: 'api[_-]?key\s*[:=]\s*["\'][\w\-]{20,}["\']'
    description: "Generic API key in configuration"

  - name: Generic Secret
    regex: 'secret\s*[:=]\s*["\'][\w\-@!#$%^&*()]{12,}["\']'
    description: "Generic secret field in configuration"

  - name: Private Key Header
    regex: '-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----'
    description: "Private key file header"

  - name: JWT Token
    regex: 'eyJ[a-zA-Z0-9_-]+\.eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+'
    description: "JSON Web Token (JWT)"

# File patterns to always scan
scan_paths:
  - '**/*.py'
  - '**/*.js'
  - '**/*.ts'
  - '**/*.json'
  - '**/*.yml'
  - '**/*.yaml'
  - '**/*.env*'
  - '**/*.conf'
  - '**/*.config'
  - '**/*.sh'

# Paths to exclude from scanning
exclude_paths:
  - '**/node_modules/**'
  - '**/venv/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.git/**'
  - '**/test/**'
  - '**/tests/**'
  - '**/__pycache__/**'
