// Danger.js configuration for automated PR reviews
// Part of INSA Automation Corp GitHub automation system
// Generated: November 14, 2025

const { danger, fail, warn, message, markdown } = require('danger');

// PR metadata
const pr = danger.github.pr;
const modified = danger.git.modified_files;
const created = danger.git.created_files;
const deleted = danger.git.deleted_files;
const allFiles = [...modified, ...created];

// === PR SIZE CHECKS ===
const bigPRThreshold = 500;
const changedLines = pr.additions + pr.deletions;

if (changedLines > bigPRThreshold) {
  warn(`This PR has ${changedLines} lines changed. Consider breaking it into smaller PRs for easier review.`);
}

// === SECURITY CHECKS ===
// Check for potential secrets or credentials
const secretPatterns = [
  /password\s*=\s*['"][^'"]+['"]/gi,
  /api[_-]?key\s*=\s*['"][^'"]+['"]/gi,
  /secret\s*=\s*['"][^'"]+['"]/gi,
  /token\s*=\s*['"][^'"]+['"]/gi,
  /-----BEGIN (RSA|DSA|EC) PRIVATE KEY-----/i,
];

allFiles.forEach(file => {
  if (file.endsWith('.json') || file.endsWith('.js') || file.endsWith('.py') || file.endsWith('.yaml') || file.endsWith('.yml')) {
    secretPatterns.forEach(pattern => {
      const fileContent = danger.git.JSONDiffForFile(file);
      if (fileContent && pattern.test(JSON.stringify(fileContent))) {
        fail(`⚠️ Potential secret detected in ${file}. Please review carefully!`);
      }
    });
  }
});

// === DOCUMENTATION CHECKS ===
const hasChangedCode = allFiles.some(f => f.endsWith('.py') || f.endsWith('.js') || f.endsWith('.ts'));
const hasChangedDocs = allFiles.some(f => f.endsWith('.md') || f.includes('README'));

if (hasChangedCode && !hasChangedDocs && !pr.title.includes('[skip-docs]')) {
  warn('📝 Code changes detected without documentation updates. Consider updating docs or adding `[skip-docs]` to PR title.');
}

// === TESTING CHECKS ===
const hasChangedTests = allFiles.some(f => f.includes('test') || f.includes('spec'));

if (hasChangedCode && !hasChangedTests && !pr.title.includes('[skip-tests]')) {
  warn('🧪 Code changes detected without test updates. Consider adding tests or adding `[skip-tests]` to PR title.');
}

// === FILE PATTERN CHECKS ===
// Check for unintentional file additions
const unwantedPatterns = [
  { pattern: /\.env$/, message: 'Environment files should not be committed' },
  { pattern: /\.log$/, message: 'Log files should not be committed' },
  { pattern: /node_modules\//, message: 'node_modules should not be committed' },
  { pattern: /__pycache__\//, message: '__pycache__ should not be committed' },
  { pattern: /\.pyc$/, message: 'Compiled Python files should not be committed' },
  { pattern: /\.DS_Store$/, message: '.DS_Store files should not be committed' },
];

created.forEach(file => {
  unwantedPatterns.forEach(({ pattern, message: msg }) => {
    if (pattern.test(file)) {
      fail(`❌ ${msg}: ${file}`);
    }
  });
});

// === COMMIT MESSAGE CHECKS ===
const commits = danger.github.commits;
const invalidCommits = commits.filter(commit => {
  const msg = commit.commit.message;
  // Check for conventional commit format
  const conventionalPattern = /^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)(\(.+\))?: .+/;
  return !conventionalPattern.test(msg) && !msg.includes('Merge');
});

if (invalidCommits.length > 0) {
  warn(`📋 ${invalidCommits.length} commit(s) don't follow conventional commit format. Consider using: feat|fix|docs|style|refactor|test|chore`);
}

// === PERFORMANCE CHECKS ===
// Check for large file additions
const largeFileThreshold = 1000000; // 1MB
created.forEach(file => {
  const stat = danger.git.fileMatch(file);
  if (stat && stat.additions > largeFileThreshold / 100) {
    warn(`📦 Large file added: ${file}. Consider using Git LFS for large files.`);
  }
});

// === SUMMARY MESSAGE ===
markdown(`
## PR Review Summary 🤖

**Changed Lines:** ${pr.additions} additions, ${pr.deletions} deletions
**Files Modified:** ${modified.length} modified, ${created.length} created, ${deleted.length} deleted

**Automated Checks:**
- ✅ Secret scanning
- ✅ Documentation coverage
- ✅ Test coverage
- ✅ File pattern validation
- ✅ Commit message format
- ✅ Large file detection

*Generated by Danger.js - Part of INSA Automation Corp CI/CD pipeline*
`);

// === HELPFUL SUGGESTIONS ===
if (pr.additions + pr.deletions < 10) {
  message('👍 Small PR - easy to review!');
}

if (pr.title.toLowerCase().includes('wip') || pr.title.toLowerCase().includes('draft')) {
  warn('🚧 This PR is marked as WIP/Draft. Remember to mark it ready when complete.');
}
