name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - WilBtc

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (blocking work)
        - High (very important)
        - Medium (nice to have)
        - Low (future enhancement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      options:
        - GitHub CI Fixer
        - Autonomous Orchestrator
        - MCP Servers
        - INSA CRM Platform
        - Azure Monitor
        - Security Stack
        - Documentation
        - New Component
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, etc.
